export const ADD_CREATURE = 'ADD_CREATURE'
export const ADD_MONSTERS = 'ADD_MONSTERS'
export const REMOVE_CREATURE = 'REMOVE_CREATURE'
export const ROLL_INITIATIVE = 'ROLL_INITIATIVE'
export const SET_STATE_FROM_LOCAL = 'SET_STATE_FROM_LOCAL'

export const LOCAL_CREATURES = 'LOCAL_CREATURES'
