export const DAMAGE_CREATURE = 'DAMAGE_CREATURE'
export const HEAL_CREATURE = 'HEAL_CREATURE'

export const ADD_CREATURES_TO_STATE = 'ADD_CREATURES_TO_STATE'
export const REMOVE_CREATURE_FROM_STATE = 'REMOVE_CREATURES_FROM_STATE'

export const DECREMENT_PLAYER_COUNT = 'DECREMENT_PLAYER_COUNT'
export const INCREMENT_PLAYER_COUNT = 'INCREMENT_PLAYER_COUNT'

export const DECREMENT_GROUP_INITIATIVE_ORDER = 'DECREMENT_GROUP_INITIATIVE_ORDER'
export const INCREMENT_GROUP_INITIATIVE_ORDER = 'INCREMENT_GROUP_INITIATIVE_ORDER'

export const ROLL_INITIATIVE = 'ROLL_INITIATIVE'

export const LOCAL_CREATURES = 'LOCAL_CREATURES'

// Conditions
export const ADD_CUSTOM_CONDITION = 'ADD_CUSTOM_CONDITION'
export const REMOVE_CUSTOM_CONDITION = 'REMOVE_CUSTOM_CONDITION'

export const SET_EXHAUSTION_LEVEL = 'SET_EXHAUSTION_LEVEL'

export const TOGGLE_CONDITION = 'TOGGLE_CONDITION'
