export const ADD_CREATURES = 'ADD_CREATURES'
export const REMOVE_CREATURE = 'REMOVE_CREATURE'

export const INCREMENT_PLAYER_COUNT = 'INCREMENT_PLAYER_COUNT'
export const DECREMENT_PLAYER_COUNT = 'DECREMENT_PLAYER_COUNT'

export const DECREMENT_CREATURE_INITIATIVE = 'DECREMENT_CREATURE_INITIATIVE'
export const INCREMENT_CREATURE_INITIATIVE = 'INCREMENT_CREATURE_INITIATIVE'

export const ROLL_INITIATIVE = 'ROLL_INITIATIVE'
export const SET_STATE_FROM_LOCAL = 'SET_STATE_FROM_LOCAL'

export const LOCAL_CREATURES = 'LOCAL_CREATURES'

// Next gen (not implemented)
export const ADD_CREATURES_TO_STATE = 'ADD_CREATURES_TO_STATE'
export const REMOVE_CREATURES_FROM_STATE = 'REMOVE_CREATURES_FROM_STATE'
